"""Configuration for the native Discord roster workflow."""

from __future__ import annotations

from pathlib import Path


DB_PATH = Path("data/rosters/rosters.sqlite3")
SCHEDULER_INTERVAL_SECONDS = 60
REFRESH_COOLDOWN_SECONDS = 30
ROSTER_SEARCH_CACHE_TTL_SECONDS = 60
ROSTER_SEARCH_INITIAL_WAIT_SECONDS = 1.0
ROSTER_ROWS_PER_PAGE = 50
ROSTER_EMOJI_ROWS_PER_PAGE = 40
ROSTER_SELECTOR_PAGE_SIZE = 25
ROSTER_PLAYER_COLUMN_WIDTH = 14
ROSTER_DISCORD_COLUMN_WIDTH = 10
ROSTER_CLAN_COLUMN_WIDTH = 4
ROSTER_PLAYER_COLUMN_MIN_WIDTH = 6
ROSTER_PLAYER_COLUMN_MAX_WIDTH = 24
ROSTER_DISCORD_COLUMN_MIN_WIDTH = 7
ROSTER_DISCORD_COLUMN_MAX_WIDTH = 20
DEFAULT_MAX_MEMBERS = 500
MAX_ROSTER_MEMBERS = 500
FAMILY_CLAN_CODE = "FAMILY"
FAMILY_DISPLAY_NAME = "Brown Elbow Clan Family"
CWL_SIGNUP_ROSTER_ID = 1
CWL_CLAN_ROSTER_IDS = {
    "BEH": 4,
    "BE4": 5,
    "BES": 6,
    "BE1": 7,
    "BEM": 8,
    "BEC": 9,
    "BEP": 10,
    "BEE": 11,
}
