"""Fixed text shown by the agent."""

FAILURE_MESSAGE = "I couldn't finish that right now. Try again in a moment."
LONG_REPLY_FILENAME = "Elbow Helper.txt"
SPREADSHEET_FILENAME_STEM = "spreadsheet"

COMMAND_MISSING_VALUE = "I still need:\n{values}"
COMMAND_PRIVATE_NOTE = "Result is ready. Open it privately below."
COMMAND_PRIVATE_BUTTON = "View result"
COMMAND_EMPTY = "That command found nothing to show."
COMMAND_UNAVAILABLE = "I couldn't run that command."
COMMAND_RESULT_EXPIRED = "That result has expired. Run the request again."
COMMAND_RESULT_OWNER = "Only the member who asked can open this result."

COMMAND_PREVIEW_HEADER = "Confirm these changes:"
COMMAND_CONFIRM_BUTTON = "Confirm"
COMMAND_CANCEL_BUTTON = "Cancel"
COMMAND_CANCELLED = "Cancelled."
COMMAND_PREVIEW_EXPIRED = "This preview has expired. Run the request again."
COMMAND_PREVIEW_OWNER = "Only the member who asked can confirm this."
COMMAND_PREVIEW_CHANGED = "The data changed since this preview. Ask again to see an updated one."
COMMAND_PREVIEW_USED = "This was already confirmed or cancelled."
COMMAND_CONFIRM_FAILED = "Done: {finished}. Not done: {remaining}."
COMMAND_NO_CHANGES = "none"
ACTION_PREVIEW_SUMMARY = "{index}. {name}: {count} {unit}"
ACTION_PREVIEW_UNIT_ONE = "change"
ACTION_PREVIEW_UNIT_MANY = "changes"
ACTION_CANNOT_UNDO = "This can't be undone."
ACTION_RUNNING = "Running {count} {unit}..."
ACTION_PROGRESS = "{done} of {total} done..."
ACTION_RUN_DONE = "Done: {finished}."
ACTION_STOP_BUTTON = "Stop"
ACTION_STOP_OWNER = "Only the member who confirmed can stop this."
ACTION_DISCORD_PERMISSION = "I couldn't finish this change. The bot needs {permission}."
ACTION_UNNAMED_PERMISSION = "the required permission"
ACTION_TEMPORARY_FAILURE = "The last change may still be going through. Ask me to check before trying again."
ACTION_AUDIT_REASON = "Requested by {member} ({member_id}) through Elbow Helper."
ACTION_UNDO_CHANGED = "This has changed since then."
ACTION_ROLE_ADD_LINE = "Add {role} to {member}."
ACTION_ROLE_REMOVE_LINE = "Remove {role} from {member}."
ACTION_ROLE_ADD_DONE = "Added {role} for {member}."
ACTION_ROLE_REMOVE_DONE = "Removed {role} for {member}."
ACTION_ROLE_ADD_LABEL = "Add role"
ACTION_ROLE_REMOVE_LABEL = "Remove role"
ACTION_ROLE_UNDO_LABEL = "Undo role change"
ACTION_POST_LINE = "Post in {channel}:"
ACTION_POST_FUTURE_LINE = "Post in the channel from the earlier action ({step}):"
ACTION_POST_LABEL = "Post message"
ACTION_POST_DONE = "Posted in {channel}."
ACTION_EDIT_LINE = "Edit message in {channel}:"
ACTION_EDIT_LABEL = "Edit message"
ACTION_EDIT_DONE = "Edited the message in {channel}."
ACTION_DELETE_LINE = "Delete this message from {channel}:"
ACTION_DELETE_LABEL = "Delete message"
ACTION_DELETE_DONE = "Deleted the message from {channel}."
ACTION_PINGS_LINE = "Pings: {targets}"
ACTION_ATTACH_LINE = "Attach {filename}"
ACTION_THREAD_CREATE_LINE = "Create thread {name} in {channel}."
ACTION_THREAD_CREATE_DONE = "Created {thread}."
ACTION_THREAD_CREATE_LABEL = "Create thread"
ACTION_THREAD_UPDATE_LINE = "{action} {thread}{detail}."
ACTION_THREAD_UPDATE_DONE = "{action} {thread}."
ACTION_THREAD_UPDATE_LABEL = "Change thread"
ACTION_THREAD_MEMBER_LINE = "{action} {member} {relation} {thread}."
ACTION_THREAD_MEMBER_DONE = "{action} {member} {relation} {thread}."
ACTION_THREAD_MEMBER_LABEL = "Change thread members"
ACTION_THREAD_ACTIONS = {
    "rename": ("Rename", "Renamed"),
    "archive": ("Archive", "Archived"),
    "unarchive": ("Unarchive", "Unarchived"),
    "lock": ("Lock", "Locked"),
    "unlock": ("Unlock", "Unlocked"),
}
ACTION_THREAD_MEMBER_ADD = ("Add", "Added", "to")
ACTION_THREAD_MEMBER_REMOVE = ("Remove", "Removed", "from")
ACTION_THREAD_FUTURE_TARGET = "the thread from the earlier action ({step})"
ACTION_THREAD_MEMBER_NO_CHANGE = "No thread membership change for {member}."
