"""Fixed text shown by the agent."""

FAILURE_MESSAGE = "I couldn't finish that right now. Try again in a moment."
LONG_REPLY_FILENAME = "Elbow Helper.txt"
SPREADSHEET_FILENAME_STEM = "spreadsheet"

COMMAND_MISSING_VALUE = "Which {value} should I use?"
COMMAND_PRIVATE_NOTE = "Result is ready. Open it privately below."
COMMAND_PRIVATE_BUTTON = "View result"
COMMAND_EMPTY = "That command found nothing to show."
COMMAND_UNAVAILABLE = "I couldn't run that command right now."
COMMAND_RESULT_EXPIRED = "That result has expired. Run the request again."
COMMAND_RESULT_OWNER = "Only the member who asked can open this result."

COMMAND_PREVIEW_HEADER = "Confirm these changes:"
COMMAND_PREVIEW_TOO_LONG = "I can't show the full preview here. Try fewer changes at once."
COMMAND_CONFIRM_BUTTON = "Confirm"
COMMAND_CANCEL_BUTTON = "Cancel"
COMMAND_CANCELLED = "Cancelled."
COMMAND_PREVIEW_EXPIRED = "This preview has expired. Run the request again."
COMMAND_PREVIEW_OWNER = "Only the member who asked can confirm this."
COMMAND_PREVIEW_CHANGED = "Something changed. Run the request again before confirming."
COMMAND_PREVIEW_USED = "This preview has already been handled."
COMMAND_CONFIRM_FAILED = "I couldn't finish that command. Check what changed before trying again."
