"""Fixed text shown by the agent."""

FAILURE_MESSAGE = "I couldn't finish that right now. Try again in a moment."
LONG_REPLY_FILENAME = "Elbow Helper.txt"
SPREADSHEET_FILENAME_STEM = "spreadsheet"

COMMAND_MISSING_VALUE = "Which {value_word} should I use?\n{values}"
COMMAND_PRIVATE_NOTE = "Result is ready. Open it privately below."
COMMAND_PRIVATE_BUTTON = "View result"
COMMAND_EMPTY = "That command found nothing to show."
COMMAND_UNAVAILABLE = "I couldn't run that command."
COMMAND_RESULT_EXPIRED = "That result has expired. Run the request again."
COMMAND_RESULT_OWNER = "Only the member who asked can open this result."

COMMAND_PREVIEW_HEADER = "Confirm these changes:"
COMMAND_CONFIRM_BUTTON = "Confirm"
COMMAND_CANCEL_BUTTON = "Cancel"
COMMAND_CANCELLED = "Cancelled."
COMMAND_PREVIEW_EXPIRED = "This preview has expired. Run the request again."
COMMAND_PREVIEW_OWNER = "Only the member who asked can confirm this."
COMMAND_PREVIEW_CHANGED = "The data changed since this preview. Ask again to see an updated one."
COMMAND_PREVIEW_USED = "This was already confirmed or cancelled."
COMMAND_CONFIRM_FAILED = "Finished: {finished}. Did not finish: {remaining}."
COMMAND_NO_CHANGES = "none"
