"""Local settings for achievements, economy, and raffle workflows."""

from __future__ import annotations

import re

DAILY_MSG_THRESHOLD = 5
DAILY_MIN_CHARS = 10
DAILY_REWARD = 1
DAILY_REWARD_ELDER = 4
SALARY_AMOUNT = 10
TICKET_COST = 100
TICKET_LIMIT_PER_MONTH = 1
MESSAGE_COUNT_COOLDOWN_SECONDS = 45
EMOJI_DAILY_LIMIT = 10
REACTION_DAILY_LIMIT = 15
MEME_DAILY_LIMIT = 5
MEME_COOLDOWN_SECONDS = 45
CLAN_ROLE_CHANGE_DELAY_SECONDS = 10
ACTIVE_CHANNEL_MIN_CHARS = 20
ACTIVE_CHANNEL_DAILY_LIMIT = 3
RUNTIME_CACHE_RETENTION_DAYS = 2
RUNTIME_CACHE_PRUNE_INTERVAL_SECONDS = 3600
RANDOM_CRIT_TRIGGER_RE = re.compile(r"\belbow\s+crit\b", re.IGNORECASE)
MANUAL_CAP_ENCOURAGEMENT = 10
MANUAL_CAP_CWL = 10
MANUAL_CAP_TOTAL = 20
RAFFLE_HUB_UPDATE_HOURS = 1
RAFFLE_END_CUTOFF_DAYS = 2
